-- pokemon_core.lua
-- Defines PokemonSpecies (static data) and Pokemon (runtime instances)
-- Designed for LÖVE 2D / Lua

local json = require("lib.json")  -- JSON library for parsing

--------------------------------------------------
-- PokemonSpecies (STATIC DATA)
-- Loaded from pokemon_data.json (generated by get_pokemon_data.ps1)
--------------------------------------------------

PokemonSpecies = {}
local speciesLoaded = false

-- Load Pokemon species data from JSON file
-- This should be called after love.load() or when love.filesystem is ready
local function loadPokemonSpeciesFromJSON()
    if speciesLoaded then return true end
    
    local filePath = "pokemon_data.json"
    local content = nil
    
    -- Use love.filesystem (requires love to be initialized)
    if love and love.filesystem then
        local info = love.filesystem.getInfo(filePath)
        if info then
            content = love.filesystem.read(filePath)
        end
    end
    
    if not content then
        print("[Pokemon] Warning: pokemon_data.json not found")
        return false
    end
    
    -- Strip UTF-8 BOM if present (PowerShell adds this by default)
    if content:sub(1, 3) == "\239\187\191" then
        content = content:sub(4)
    end
    
    local success, data = pcall(json.decode, content)
    if not success then
        love.filesystem.write("pokemon_debug.txt", table.concat(debugLog, "\n") .. "\nJSON Error: " .. tostring(data))
        return false
    end
    
    -- Process each Pokemon entry
    for name, pokemonData in pairs(data) do
        -- Convert learnset keys from strings to numbers
        local convertedLearnset = {}
        if pokemonData.learnset then
            for levelStr, moves in pairs(pokemonData.learnset) do
                local level = tonumber(levelStr)
                if level then
                    convertedLearnset[level] = moves
                end
            end
        end
        pokemonData.learnset = convertedLearnset
        
        -- Handle empty evolution tables (convert {} to nil)
        if pokemonData.evolution and next(pokemonData.evolution) == nil then
            pokemonData.evolution = nil
        end
        
        -- Use local sprite paths if the URLs are from online
        local pokemonNameClean = name:gsub("-", "_")
        if pokemonData.sprite then
            -- Check if sprites are URLs (start with http)
            if pokemonData.sprite.front and pokemonData.sprite.front:match("^http") then
                pokemonData.sprite.front = "tiled/sprites/pokemon_front/" .. pokemonNameClean .. ".png"
            end
            if pokemonData.sprite.back and pokemonData.sprite.back:match("^http") then
                pokemonData.sprite.back = "tiled/sprites/pokemon_back/" .. pokemonNameClean .. ".png"
            end
        else
            pokemonData.sprite = {
                front = "tiled/sprites/pokemon_front/" .. pokemonNameClean .. ".png",
                back = "tiled/sprites/pokemon_back/" .. pokemonNameClean .. ".png"
            }
        end
        
        -- Capitalize the display name
        pokemonData.name = pokemonData.name:gsub("^%l", string.upper):gsub("_%l", function(s) return " " .. s:sub(2):upper() end)
        
        -- Store in PokemonSpecies table
        PokemonSpecies[name] = pokemonData
    end
    
    -- Count loaded species
    local count = 0
    for _ in pairs(PokemonSpecies) do count = count + 1 end
    print("[Pokemon] Loaded " .. count .. " Pokemon species from JSON")
    speciesLoaded = true
    return true
end

-- Expose the load function so it can be called from love.load()
local function initPokemonSpecies()
    return loadPokemonSpeciesFromJSON()
end

-- Fallback/custom Pokemon that aren't in the JSON (for testing, etc.)
local fallbackPokemon = {
    --------------------------------------------------
    -- TEST POKEMON (for debugging)
    --------------------------------------------------
    exp_dummy = {
        id = 9999,
        name = "EXP Dummy",
        types = {"normal"},
        genderRatio = { male = 50, female = 50 },
        catchRate = 255,
        baseExpYield = 5000,  -- Gives tons of EXP!
        baseFriendship = 70,
        growthRate = "fast",
        abilities = {"run_away"},
        hiddenAbility = nil,
        baseStats = {
            hp = 1,      -- Dies in one hit
            attack = 1,
            defense = 1,
            spAttack = 1,
            spDefense = 1,
            speed = 1
        },
        learnset = {
            [1] = {"splash"}
        },
        evolution = nil,
        sprite = {
            front = "tiled/sprites/pokemon_front/exp_dummy.png",
            back  = "tiled/sprites/pokemon_back/exp_dummy.png"
        }
    },

    -- Custom grass-squirrel evolution line (three stages)
    grass_squirrel = {
        id = 10001,
        name = "Grass Squirrel",
        types = {"grass"},
        genderRatio = { male = 50, female = 50 },
        catchRate = 190,
        baseExpYield = 64,
        baseFriendship = 70,
        growthRate = "medium_fast",
        abilities = {"leaf_guard"},
        hiddenAbility = "pickup",
        baseStats = {
            hp = 40,
            attack = 45,
            defense = 40,
            spAttack = 35,
            spDefense = 40,
            speed = 50
        },
        learnset = {
            [1] = {"tackle", "tail_whip"},
            [5] = {"growth"},
            [9] = {"razor_leaf"},
            [13] = {"quick_attack"}
        },
        evolution = { method = "level", level = 16, into = "grass_squirrel_mid" },
        sprite = {
            front = "tiled/sprites/newpokemon/4.png",
            back  = "tiled/sprites/newpokemon/4.png"
        }
    },

    grass_squirrel_mid = {
        id = 10002,
        name = "Bushrod",
        types = {"grass"},
        genderRatio = { male = 50, female = 50 },
        catchRate = 120,
        baseExpYield = 142,
        baseFriendship = 70,
        growthRate = "medium_fast",
        abilities = {"overgrow"},
        hiddenAbility = "pickup",
        baseStats = {
            hp = 60,
            attack = 70,
            defense = 60,
            spAttack = 55,
            spDefense = 60,
            speed = 65
        },
        learnset = {
            [1] = {"tackle", "tail_whip", "growth"},
            [16] = {"leaf_blade"},
            [22] = {"synthesis"},
            [28] = {"seed_bomb"}
        },
        evolution = { method = "level", level = 36, into = "grass_squirrel_final" },
        sprite = {
            front = "tiled/sprites/newpokemon/5.png",
            back  = "tiled/sprites/newpokemon/5.png"
        }
    },

    grass_squirrel_final = {
        id = 10003,
        name = "Oakquill",
        types = {"grass"},
        genderRatio = { male = 50, female = 50 },
        catchRate = 45,
        baseExpYield = 236,
        baseFriendship = 70,
        growthRate = "medium_fast",
        abilities = {"chlorophyll"},
        hiddenAbility = "leaf_guard",
        baseStats = {
            hp = 85,
            attack = 100,
            defense = 85,
            spAttack = 75,
            spDefense = 85,
            speed = 90
        },
        learnset = {
            [1] = {"tackle", "tail_whip", "leaf_blade", "synthesis"},
            [36] = {"wood_hammer"},
            [44] = {"leaf_storm"},
            [52] = {"horn_leech"}
        },
        evolution = nil,
        sprite = {
            front = "tiled/sprites/newpokemon/6.png",
            back  = "tiled/sprites/newpokemon/6.png"
        }
    }
,
    -- Custom fire-bird evolution line (three stages) based on "cardinel"
    cardinel = {
        id = 10011,
        name = "Cardinel",
        types = {"fire", "flying"},
        genderRatio = { male = 50, female = 50 },
        catchRate = 45,
        baseExpYield = 64,
        baseFriendship = 70,
        growthRate = "medium_fast",
        abilities = {"gale_wings"},
        hiddenAbility = "flame_body",
        baseStats = {
            hp = 45,
            attack = 60,
            defense = 35,
            spAttack = 50,
            spDefense = 35,
            speed = 65
        },
        learnset = {
            [1] = {"peck", "ember"},
            [7] = {"wing_attack"},
            [12] = {"flame_charge"}
        },
        evolution = { method = "level", level = 18, into = "cardinel_mid" },
        sprite = {
            front = "tiled/sprites/newpokemon/1.png",
            back  = "tiled/sprites/newpokemon/1.png"
        }
    },

    cardinel_mid = {
        id = 10012,
        name = "Cardifire",
        types = {"fire", "flying"},
        genderRatio = { male = 50, female = 50 },
        catchRate = 30,
        baseExpYield = 142,
        baseFriendship = 70,
        growthRate = "medium_fast",
        abilities = {"gale_wings"},
        hiddenAbility = "flame_body",
        baseStats = {
            hp = 65,
            attack = 85,
            defense = 55,
            spAttack = 85,
            spDefense = 55,
            speed = 95
        },
        learnset = {
            [1] = {"peck", "ember", "wing_attack", "flame_charge"},
            [18] = {"air_slash"},
            [28] = {"flamethrower"}
        },
        evolution = { method = "level", level = 38, into = "cardinel_final" },
        sprite = {
            front = "tiled/sprites/newpokemon/2.png",
            back  = "tiled/sprites/newpokemon/2.png"
        }
    },

    cardinel_final = {
        id = 10013,
        name = "Cardignis",
        types = {"fire", "flying"},
        genderRatio = { male = 50, female = 50 },
        catchRate = 20,
        baseExpYield = 240,
        baseFriendship = 70,
        growthRate = "medium_fast",
        abilities = {"gale_wings"},
        hiddenAbility = "flame_body",
        baseStats = {
            hp = 90,
            attack = 120,
            defense = 80,
            spAttack = 115,
            spDefense = 80,
            speed = 110
        },
        learnset = {
            [1] = {"peck", "ember", "air_slash", "flamethrower"},
            [36] = {"flare_blitz"},
            [44] = {"heat_wave"},
            [52] = {"brave_bird"}
        },
        evolution = nil,
        sprite = {
            front = "tiled/sprites/newpokemon/3.png",
            back  = "tiled/sprites/newpokemon/3.png"
        }
    }
}

-- Merge fallback Pokemon into PokemonSpecies (won't override loaded ones)
for name, data in pairs(fallbackPokemon) do
    if not PokemonSpecies[name] then
        PokemonSpecies[name] = data
    end
end

-- Helper functions (not added to PokemonSpecies table to avoid iteration issues)
local PokemonSpeciesHelpers = {}

-- Function to get species count
function PokemonSpeciesHelpers.getCount()
    local count = 0
    for _ in pairs(PokemonSpecies) do
        count = count + 1
    end
    return count
end

-- Function to get species by ID number
function PokemonSpeciesHelpers.getById(id)
    for name, species in pairs(PokemonSpecies) do
        if type(species) == "table" and species.id == id then
            return species, name
        end
    end
    return nil
end

--------------------------------------------------
-- Pokemon (RUNTIME INSTANCE)
--------------------------------------------------

Pokemon = {}
Pokemon.__index = Pokemon

function Pokemon:new(speciesId, level)
    local species = PokemonSpecies[speciesId]
    assert(species, "Unknown Pokemon species: " .. tostring(speciesId))

    local p = {
        speciesId = speciesId,
        species = species,
        name = species.name,
        nickname = species.name,
        level = level or 1,
        exp = 0,  -- will be set after calculating stats
        nature = "hardy",
        gender = Pokemon:rollGender(species.genderRatio),
        ability = species.abilities[1],
        friendship = species.baseFriendship,
        shiny = (math.random(1, 4096) == 1),
        ivs = {
            hp = math.random(0, 31),
            attack = math.random(0, 31),
            defense = math.random(0, 31),
            spAttack = math.random(0, 31),
            spDefense = math.random(0, 31),
            speed = math.random(0, 31)
        },
        evs = {
            hp = 0,
            attack = 0,
            defense = 0,
            spAttack = 0,
            spDefense = 0,
            speed = 0
        },
        status = nil,
        moves = {},
        heldItem = nil
    }

    setmetatable(p, Pokemon)

    p.stats = p:calculateStats()
    p.currentHP = p.stats.hp
    p:learnMovesForLevel()
    
    -- Initialize exp to the cumulative total for this level
    p.exp = p:getExpForLevel(p.level)

    return p
end

-- Reconstruct a Pokemon instance from saved data (after loading from JSON)
-- This ensures the metatable is set and methods are available
function Pokemon.fromSavedData(data)
    if not data or not data.speciesId then
        return nil
    end
    
    local species = PokemonSpecies[data.speciesId]
    if not species then
        return nil
    end
    
    -- Create a new instance with the saved data
    local p = {}
    for k, v in pairs(data) do
        p[k] = v
    end
    
    -- Ensure species reference is set
    p.species = species
    
    -- Add name property from species if not already set (for menu.lua compatibility)
    if not p.name then
        p.name = species.name
    end
    
    -- Set the metatable so methods are available
    setmetatable(p, Pokemon)
    
    return p
end

--------------------------------------------------
-- Pokemon Methods
--------------------------------------------------

function Pokemon:rollGender(ratio)
    if not ratio then return "genderless" end
    local roll = math.random() * 100
    return (roll <= ratio.male) and "male" or "female"
end

function Pokemon:calculateStats()
    local stats = {}
    local base = self.species.baseStats
    local lvl = self.level
    local evs = self.evs or { hp = 0, attack = 0, defense = 0, spAttack = 0, spDefense = 0, speed = 0 }

    -- HP formula: floor((2*Base + IV + floor(EV/4)) * Level / 100) + Level + 10
    stats.hp = math.floor(((2 * base.hp + self.ivs.hp + math.floor(evs.hp / 4)) * lvl) / 100) + lvl + 10

    -- Other stats: floor((2*Base + IV + floor(EV/4)) * Level / 100) + 5
    for _, stat in ipairs({"attack", "defense", "spAttack", "spDefense", "speed"}) do
        local evVal = evs[stat] or 0
        stats[stat] = math.floor(((2 * base[stat] + self.ivs[stat] + math.floor(evVal / 4)) * lvl) / 100) + 5
    end

    return stats
end

function Pokemon:learnMovesForLevel()
    for lvl, moveList in pairs(self.species.learnset) do
        if lvl <= self.level then
            for _, moveId in ipairs(moveList) do
                self:learnMove(moveId)
            end
        end
    end
end

function Pokemon:learnMove(moveId)
    for _, m in ipairs(self.moves) do
        if m == moveId then return end
    end

    if #self.moves >= 4 then return end
    table.insert(self.moves, moveId)
end

function Pokemon:isFainted()
    return self.currentHP <= 0
end

function Pokemon:heal(amount)
    self.currentHP = math.min(self.currentHP + amount, self.stats.hp)
end

function Pokemon:takeDamage(amount)
    self.currentHP = math.max(self.currentHP - amount, 0)
end

function Pokemon:gainExp(amount)
    self.exp = self.exp + amount
    local levelsGained = {}
    local pendingEvolution = nil
    -- Check for level ups
    while self.level < 100 do
        local expForNext = self:getExpForLevel(self.level + 1)
        if self.exp >= expForNext then
            table.insert(levelsGained, self.level + 1)
            self:levelUp()
            -- Check if Pokemon can evolve after this level up
            local canEvolve, evolveInto = self:canEvolveByLevel()
            if canEvolve then
                pendingEvolution = evolveInto
            end
        else
            break
        end
    end
    return levelsGained, pendingEvolution
end

-- Calculate total experience needed to reach a specific level based on growth rate
function Pokemon:getExpForLevel(level)
    if level <= 1 then return 0 end
    
    local rate = self.species.growthRate
    local exp
    
    if rate == "fast" then
        -- 0.8 * n^3
        exp = math.floor(0.8 * level * level * level)
    elseif rate == "medium_fast" then
        -- n^3
        exp = level * level * level
    elseif rate == "medium_slow" then
        -- 1.2*n^3 - 15*n^2 + 100*n - 140
        exp = math.floor(1.2 * level * level * level - 15 * level * level + 100 * level - 140)
    elseif rate == "slow" then
        -- 1.25 * n^4
        exp = math.floor(1.25 * level * level * level * level)
    else
        -- fallback to medium_fast
        exp = level * level * level
    end
    
    return math.max(0, exp)
end

-- Handle leveling up: recalculate stats and learn new moves
function Pokemon:levelUp()
    self.level = self.level + 1
    -- Recalculate stats for the new level
    self.stats = self:calculateStats()
    -- Cap current HP to new max
    if self.currentHP > self.stats.hp then
        self.currentHP = self.stats.hp
    end
    -- Learn moves for this level
    self:learnMovesForLevel()
end

-- Calculate experience yield from defeating another Pokémon
-- Formula based on official Pokémon games
function Pokemon.calculateExpYield(defeatedPokemon, winnerLevel)
    if not defeatedPokemon or not defeatedPokemon.species then
        return 0
    end
    
    local baseExp = defeatedPokemon.species.baseExpYield or 0
    local defeatedLevel = defeatedPokemon.level or 1
    
    -- Basic formula: (baseExp * defeatedLevel) / 7
    local exp = math.floor((baseExp * defeatedLevel) / 7)
    
    -- Apply level scaling: penalize overleveled Pokémon, bonus for underleveled
    if winnerLevel and winnerLevel > defeatedLevel then
        -- Penalty for overleveled trainer
        exp = math.floor(exp * (2 * defeatedLevel + 5) / (winnerLevel + defeatedLevel + 5))
    elseif winnerLevel and winnerLevel < defeatedLevel then
        -- Bonus for underleveled trainer
        exp = math.floor(exp * (2 * defeatedLevel + 5) / (winnerLevel + defeatedLevel + 5))
    end
    
    return math.max(1, exp)
end

function Pokemon:__tostring()
    return self.nickname or "Pokemon"
end

-- Check if this Pokemon can evolve by level
function Pokemon:canEvolveByLevel()
    local evo = self.species.evolution
    if not evo then return false end
    if evo.method == "level" and evo.level and self.level >= evo.level then
        return true, evo.into
    end
    return false
end

-- Check if this Pokemon can evolve with a specific item
function Pokemon:canEvolveWithItem(itemId)
    local evo = self.species.evolution
    if not evo then return false end
    
    if evo.method == "item" and evo.item == itemId then
        return true, evo.into
    end
    
    -- Handle branching evolutions (like Eevee)
    if evo.method == "branch" and evo.options then
        for _, opt in ipairs(evo.options) do
            if opt.method == "item" and opt.item == itemId then
                return true, opt.into
            end
        end
    end
    
    return false
end

-- Evolve this Pokemon into a new species
function Pokemon:evolve(newSpeciesId)
    local newSpecies = PokemonSpecies[newSpeciesId]
    if not newSpecies then
        return false, "Unknown species: " .. tostring(newSpeciesId)
    end
    
    local oldName = self.nickname
    local oldSpeciesName = self.species.name
    
    -- Update species
    self.speciesId = newSpeciesId
    self.species = newSpecies
    self.name = newSpecies.name
    
    -- Update nickname if it was the old species name
    if self.nickname == oldSpeciesName then
        self.nickname = newSpecies.name
    end
    
    -- Recalculate stats for the new species
    self.stats = self:calculateStats()
    
    -- Learn any new moves from the new species' learnset
    self:learnMovesForLevel()
    
    return true, oldName .. " evolved into " .. newSpecies.name .. "!"
end

return {
    PokemonSpecies = PokemonSpecies,
    PokemonSpeciesHelpers = PokemonSpeciesHelpers,
    Pokemon = Pokemon,
    init = initPokemonSpecies  -- Call this after love.load() to load species from JSON
}

